" general
set number
set relativenumber
set list
set tabstop=2
set shiftwidth=2
set listchars=eol:¬,tab:⌥˼,trail:˼,nbsp:˽,space:·
" plugins
call plug#begin()
Plug 'tpope/vim-dispatch'
call plug#end()
